### ISSUE TITLE
Is this repo for the Chinese only? 

### ISSUE THREAD

**Issue by pe200012** [awesome-OI/awesome-OI#4]
Most `awesome-` projects are in English, and therefore they can receive contributions from all over the world.

If we want this repo to develop quickly, maybe we should change the language?

**Comment by HRiver2** [comment]
我个人觉得应当以英文为主，不过可以加上中文注释

I personally think that English should be the main language, but Chinese annotations can be added

**Comment by HRiver2** [comment]
毕竟 awesome.re 那里我还没看到有中文的，个人觉得如果全做中文可能会不被收录？

但是确实英语对于这个 Project 发展确实不是很有利，毕竟本来就是中国OIer建立的（

或者是贡献者贡献时以中文为主，然后再逐步翻译？这样或许能够提高贡献者的积极性（

~~原谅我英语太差，自己说的话都翻译不出来，只能用生草机~~
